### ISSUE TITLE
Убрать комментарии

### ISSUE THREAD

**Issue by coursar** [KarenKiK/HWCalculateWalppaper#5]
https://github.com/KarenKiK/HWCalculateWalppaper/blob/5cbfbfb35610af257870f1e35f3954e6d6124067/src/main/java/ru/itpark/calculateWalpaper/service/CalculateWallpaperService.java#L8-L17

**Comment by KarenKiK** [comment]
Сделанно

**Comment by KarenKiK** [comment]
Сделанно
